import Head from "next/head";
import Image from "next/image";
import Navbar from "./navbar";

const Home = () => {
  const socials = [
    {
      imageUrl: "/icons/email.svg",
      title: "Email",
      link: "mailto:johnfulky@mac.com",
    },
    {
      imageUrl: "/icons/github.svg",
      title: "GitHub",
      link: "https://github.com/JTFulkerson",
    },
    {
      imageUrl: "/icons/linkedin.svg",
      title: "LinkedIn",
      link: "https://www.linkedin.com/in/jtfulkerson/",
    },
    {
      imageUrl: "/icons/instagram.svg",
      title: "Instagram",
      link: "https://www.instagram.com/jt_fulkerson/",
    },
    {
      imageUrl: "/icons/twitter.svg",
      title: "Twitter",
      link: "https://twitter.com/JT_Fulkerson",
    },
    {
      imageUrl: "/icons/facebook.svg",
      title: "Facebook",
      link: "https://www.facebook.com/john.fulkerson.98837/",
    }
  ];

  return (
    <>
      <Head>
        <title>John Fulkerson | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="py-12 px-12">
        <div className="grid sm:grid-cols-2 w-fit h-fit">
          <Image
            src="/images/headshot.png"
            alt=""
            className="h-full w-full"
            height={1000}
            width={1000}
            priority
          ></Image>
          <div className="flex justify-center items-center pl-10">
            <div>
              <h1 className="text-left text-[8vw] leading-none">John</h1>
              <h1 className="text-left text-[8vw] leading-none">Fulkerson</h1>
              <h2 className="text-left text-[1.8vw] pb-3">
                BS Computer Science | University of Delaware ’26
              </h2>
              <div className="grid grid-flow-col">
                {socials.map((social) => (
                  <a
                    href={social.link}
                    key={social.title}
                  >
                    <Image
                      src={social.imageUrl}
                      alt=""
                      className="1vw p-1 hover:drop-shadow-xl hover:pt-0"
                      width={100}
                      height={24}
                      priority
                    />
                  </a>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Home;